<a href="https://colab.research.google.com/github/mohammedshamilm7890/real-time-stock-market-prediction/blob/main/another_level_of_real_time_stock_market_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import yfinance as yf
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from datetime import datetime, timedelta
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
company_symbols = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA','NVDA','JPM','GS','WMT','KO']
end_date = datetime.now()
start_date = end_date - timedelta(days=365)
start_date

datetime.datetime(2025, 4, 25, 2, 58, 49, 171105)

In [ ]:
company_data = {}
for symbol in company_symbols:
    df = yf.download(symbol, start=start_date, end=end_date)
    company_data[symbol] = df

/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_1586/2902190649.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

In [ ]:
company_data

{'AAPL': Price            Close        High         Low        Open    Volume
 Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
 Date
 2025-04-25  208.371826  208.839788  205.305190  205.474450  38222300
 2025-04-28  209.228104  210.582203  206.559741  209.088712  38743100
 2025-04-29  210.293457  211.318986  207.465770  207.784388  36827600
 2025-04-30  211.577850  212.653165  205.773148  208.391740  52286500
 2025-05-01  212.394318  213.628927  207.993485  208.172711  57365700
 ...                ...         ...         ...         ...       ...
 2026-04-20  273.049988  274.279999  270.290009  270.329987  36590200
 2026-04-21  266.170013  272.799988  265.399994  271.500000  50209800
 2026-04-22  273.170013  273.739990  266.869995  267.820007  43249200
 2026-04-23  273.429993  275.769989  271.649994  275.049988  33399600
 2026-04-24  271.059998  273.059998  269.649994  272.760010  38033227

 [251 rows x 5 columns],
 'MSFT': Price            Close        High         Low        Open    Volume
 Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
 Date
 2025-04-25  388.872986  389.180628  381.678067  384.059827  18973200
 2025-04-28  388.188202  389.756185  383.702553  388.982112  16579400
 2025-04-29  391.046326  392.098270  387.414129  388.327122  14974000
 2025-04-30  392.257050  393.646407  381.519246  387.334711  36461100
 2025-05-01  422.168030  433.669971  421.671829  427.834640  58938100
 ...                ...         ...         ...         ...       ...
 2026-04-20  418.070007  423.329987  416.299988  421.149994  27582200
 2026-04-21  424.160004  427.179993  417.200012  420.239990  32048500
 2026-04-22  432.920013  433.700012  423.670013  426.190002  29378200
 2026-04-23  415.750000  423.660004  411.410004  419.890015  38308000
 2026-04-24  424.619995  424.890015  415.799988  416.984985  27161742

 [251 rows x 5 columns],
 'GOOGL': Price            Close        High         Low        Open    Volume
 Ticker           GOOGL       GOOGL       GOOGL       GOOGL     GOOGL
 Date
 2025-04-25  161.400360  165.526054  160.483526  164.499614  56034000
 2025-04-28  160.055008  162.586224  158.051959  161.868711  29745800
 2025-04-29  159.606567  160.184565  156.975691  159.766018  26809000
 2025-04-30  158.251282  158.719659  154.863021  157.434108  34981100
 2025-05-01  160.742645  161.390393  158.360904  159.895576  30203200
 ...                ...         ...         ...         ...       ...
 2026-04-20  337.420013  341.399994  336.609985  340.760010  18784200
 2026-04-21  332.290009  339.339996  331.350006  337.690002  23123800
 2026-04-22  339.320007  339.820007  335.170013  337.019989  20293000
 2026-04-23  338.890015  341.959991  336.179993  341.179993  18650300
 2026-04-24  344.399994  345.269989  335.390015  338.725006  26351181

 [251 rows x 5 columns],
 'AMZN': Price            Close        High         Low        Open    Volume
 Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
 Date
 2025-04-25  188.990005  189.940002  185.490005  187.619995  36414300
 2025-04-28  187.699997  190.220001  184.889999  190.110001  33224700
 2025-04-29  187.389999  188.020004  183.679993  183.990005  41667300
 2025-04-30  184.419998  185.050003  178.850006  182.169998  55176500
 2025-05-01  190.199997  191.809998  187.500000  190.630005  74266000
 ...                ...         ...         ...         ...       ...
 2026-04-20  248.279999  250.179993  245.369995  249.190002  39463100
 2026-04-21  249.910004  255.089996  249.100006  255.089996  42922400
 2026-04-22  255.360001  255.940002  250.330002  252.440002  36065100
 2026-04-23  255.080002  258.790009  253.070007  255.389999  39091400
 2026-04-24  263.989990  264.375000  257.684998  259.880005  53601873

 [251 rows x 5 columns],
 'TSLA': Price            Close        High         Low        Open     Volume
 Ticker            TSLA        TSLA        TSLA        TSLA       TSLA
 Date
 2025-04-25  284.950012  286.850006  259.630005  261.690002  167560700
 2025-04-28  285.880005  294.859985  272.420013  288.980011  151731800
 2025-04-29  292.029999  293.320007  279.470001  285.500000  108906600
 2025-04-30  282.160004  284.450012  270.779999  279.899994  128961100
 2025-05-01  280.519989  290.869995  279.809998  280.010010   99659000
 ...                ...         ...         ...         ...        ...
 2026-04-20  392.500000  406.799988  388.329987  402.579987   64603900
 2026-04-21  386.420013  393.950012  385.220001  393.000000   50530600
 2026-04-22  387.510010  393.010010  385.299988  387.570007   62362800
 2026-04-23  373.720001  386.000000  368.390015  375.279999   93969500
 2026-04-24  376.299988  382.760010  370.734985  373.260010   62357183

 [251 rows x 5 columns],
 'NVDA': Price            Close        High         Low        Open     Volume
 Ticker            NVDA        NVDA        NVDA        NVDA       NVDA
 Date
 2025-04-25  110.983856  111.893638  105.705101  106.824832  251064700
 2025-04-28  108.704391  110.344005  105.995023  109.664164  207708500
 2025-04-29  108.994316  110.174038  107.414694  107.644636  170444300
 2025-04-30  108.894333  108.894333  104.055477  104.445385  235044600
 2025-05-01  111.583702  114.912919  111.273778  113.053357  236121500
 ...                ...         ...         ...         ...        ...
 2026-04-20  202.059998  202.169998  197.839996  199.979996  119381400
 2026-04-21  199.880005  202.750000  199.000000  202.130005  107945300
 2026-04-22  202.500000  202.500000  199.000000  200.990005  107501000
 2026-04-23  199.639999  203.830002  197.220001  202.460007  113561800
 2026-04-24  208.270004  210.949997  199.809998  199.960007  213442479

 [251 rows x 5 columns],
 'JPM': Price            Close        High         Low        Open    Volume
 Ticker             JPM         JPM         JPM         JPM       JPM
 Date
 2025-04-25  238.903793  240.934296  237.138129  239.982800   8588600
 2025-04-28  238.580078  242.131014  236.245477  239.894511   7394300
 2025-04-29  239.953384  240.571371  237.079287  237.569749   7216800
 2025-04-30  239.953384  240.541944  233.881469  236.608448  12991700
 2025-05-01  242.180084  243.710322  237.550126  238.207343   8689600
 ...                ...         ...         ...         ...       ...
 2026-04-20  316.989990  317.130005  310.369995  310.850006  10772000
 2026-04-21  313.000000  320.239990  312.750000  317.489990   7084300
 2026-04-22  313.019989  315.149994  311.940002  314.850006   5545900
 2026-04-23  311.690002  314.989990  308.890015  313.519989   6969700
 2026-04-24  308.279999  311.040009  307.890015  311.149994   5209629

 [251 rows x 5 columns],
 'GS': Price            Close        High         Low        Open   Volume
 Ticker              GS          GS          GS          GS       GS
 Date
 2025-04-25  533.801208  537.945395  530.235074  533.546476  1612700
 2025-04-28  535.309998  543.245572  531.459710  533.801216  1459700
 2025-04-29  537.778809  539.699049  530.313473  532.752925  1695600
 2025-04-30  536.436646  538.366693  520.663443  524.885963  2438300
 2025-05-01  542.589233  547.017453  534.428286  536.975491  2583000
 ...                ...         ...         ...         ...      ...
 2026-04-20  941.739990  941.799988  922.989990  923.679993  2374300
 2026-04-21  926.549988  952.010010  922.539978  944.500000  1765400
 2026-04-22  934.840027  940.979980  931.150024  939.000000  1382600
 2026-04-23  931.299988  944.390015  920.690002  935.000000  1655000
 2026-04-24  926.909973  932.914978  919.219971  930.484985  1256420

 [251 rows x 5 columns],
 'WMT': Price            Close        High         Low        Open    Volume
 Ticker             WMT         WMT         WMT         WMT       WMT
 Date
 2025-04-25   94.253647   95.621514   93.530072   94.957409  15317200
 2025-04-28   94.382507   95.155646   93.510242   94.263560  12950000
 2025-04-29   95.195290   95.334058   93.589535   94.005840  12679000
 2025-04-30   96.394646   96.919983   94.095051   95.096170  21639900
 2025-05-01   96.553246   97.038934   95.740450   96.166669  13171800
 ...                ...         ...         ...         ...       ...
 2026-04-20  127.919998  129.470001  127.320000  127.870003  18933600
 2026-04-21  129.600006  129.770004  127.480003  127.830002  17312400
 2026-04-22  129.979996  130.449997  128.839996  130.000000  17624500
 2026-04-23  132.029999  132.460007  130.490005  130.570007  16376000
 2026-04-24  129.919998  132.119995  129.281204  131.929993  15483297

 [251 rows x 5 columns],
 'KO': Price           Close       High        Low       Open    Volume
 Ticker             KO         KO         KO         KO        KO
 Date
 2025-04-25  69.884155  70.865696  69.126123  70.603306  16316000
 2025-04-28  69.767525  70.224285  69.301044  70.049356  15997500
 2025-04-29  70.311752  70.661611  68.300069  69.184436  16244100
 2025-04-30  70.506126  71.409927  69.670354  71.283584  21074700
 2025-05-01  69.281624  70.010495  69.223317  69.971621  18034200
 ...               ...        ...        ...        ...       ...
 2026-04-20  75.480003  76.220001  75.360001  75.820000  10141800
 2026-04-21  74.699997  75.529999  74.620003  75.480003  11806900
 2026-04-22  74.629997  75.379997  74.550003  74.900002   9352300
 2026-04-23  76.279999  76.660004  75.160004  75.440002  12060300
 2026-04-24  76.629997  77.004997  76.169998  76.709999  11925211

 [251 rows x 5 columns]}

In [ ]:
df

Price           Close       High        Low       Open    Volume
Ticker             KO         KO         KO         KO        KO
Date
2025-04-25  69.884155  70.865696  69.126123  70.603306  16316000
2025-04-28  69.767525  70.224285  69.301044  70.049356  15997500
2025-04-29  70.311752  70.661611  68.300069  69.184436  16244100
2025-04-30  70.506126  71.409927  69.670354  71.283584  21074700
2025-05-01  69.281624  70.010495  69.223317  69.971621  18034200
...               ...        ...        ...        ...       ...
2026-04-20  75.480003  76.220001  75.360001  75.820000  10141800
2026-04-21  74.699997  75.529999  74.620003  75.480003  11806900
2026-04-22  74.629997  75.379997  74.550003  74.900002   9352300
2026-04-23  76.279999  76.660004  75.160004  75.440002  12060300
2026-04-24  76.629997  77.004997  76.169998  76.709999  11925211

[251 rows x 5 columns]

In [ ]:
company_models={}
for symbol, data in company_data.items():
  df

In [ ]:
company_data['AAPL']

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2025-04-25  208.371826  208.839788  205.305190  205.474450  38222300
2025-04-28  209.228104  210.582203  206.559741  209.088712  38743100
2025-04-29  210.293457  211.318986  207.465770  207.784388  36827600
2025-04-30  211.577850  212.653165  205.773148  208.391740  52286500
2025-05-01  212.394318  213.628927  207.993485  208.172711  57365700
...                ...         ...         ...         ...       ...
2026-04-20  273.049988  274.279999  270.290009  270.329987  36590200
2026-04-21  266.170013  272.799988  265.399994  271.500000  50209800
2026-04-22  273.170013  273.739990  266.869995  267.820007  43249200
2026-04-23  273.429993  275.769989  271.649994  275.049988  33399600
2026-04-24  271.059998  273.059998  269.649994  272.760010  38033227

[251 rows x 5 columns]

In [ ]:
company_data['MSFT']

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2025-04-25  388.872986  389.180628  381.678067  384.059827  18973200
2025-04-28  388.188202  389.756185  383.702553  388.982112  16579400
2025-04-29  391.046326  392.098270  387.414129  388.327122  14974000
2025-04-30  392.257050  393.646407  381.519246  387.334711  36461100
2025-05-01  422.168030  433.669971  421.671829  427.834640  58938100
...                ...         ...         ...         ...       ...
2026-04-20  418.070007  423.329987  416.299988  421.149994  27582200
2026-04-21  424.160004  427.179993  417.200012  420.239990  32048500
2026-04-22  432.920013  433.700012  423.670013  426.190002  29378200
2026-04-23  415.750000  423.660004  411.410004  419.890015  38308000
2026-04-24  424.619995  424.890015  415.799988  416.984985  27161742

[251 rows x 5 columns]

In [ ]:
company_model={}
for symbol,df in company_data.items():
  df=df.copy()
  df['Target']=df['Close'].shift(-1)
  df.dropna(inplace=True)
  x=df[['Close']]
  y=df['Target']
  x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=42)
  model=LinearRegression()
  model.fit(x_train,y_train)
  company_model[symbol]=model

In [ ]:
for symbol,model in company_data.items():
   model=company_model[symbol]
   x_test=df[['Close']].tail(1)
   y_test=df['Close'].tail(1)
   y_pred=model.predict(x_test)

   mae=mean_absolute_error(y_test,y_pred)
   mse=mean_squared_error(y_test,y_pred)
   rmse=np.sqrt(mse)

   print("company: ",symbol)
   print("MAE: ",mae)
   print("MSE: ",mse)
   print("RMSE: ",rmse)
   print("*"*100)

company:  AAPL
MAE:  0.7447146702898948
MSE:  0.5545999401449867
RMSE:  0.7447146702898948
****************************************************************************************************
company:  MSFT
MAE:  4.354962178398509
MSE:  18.965695575281487
RMSE:  4.354962178398509
****************************************************************************************************
company:  GOOGL
MAE:  1.5415783665747966
MSE:  2.376463860291418
RMSE:  1.5415783665747966
****************************************************************************************************
company:  AMZN
MAE:  6.510433542165373
MSE:  42.38574490695196
RMSE:  6.510433542165373
****************************************************************************************************
company:  TSLA
MAE:  7.51139404667326
MSE:  56.42104052439849
RMSE:  7.51139404667326
****************************************************************************************************
company:  NVDA
MAE:  3.0790120605634
MSE:  9.480315269094875
RMSE:  3.0790120605634
****************************************************************************************************
company:  JPM
MAE:  10.490325884745644
MSE:  110.04693716816448
RMSE:  10.490325884745644
****************************************************************************************************
company:  GS
MAE:  13.706404410000104
MSE:  187.86552185047032
RMSE:  13.706404410000104
****************************************************************************************************
company:  WMT
MAE:  0.28970529602017336
MSE:  0.08392915854213627
RMSE:  0.28970529602017336
****************************************************************************************************
company:  KO
MAE:  0.020321643189646466
MSE:  0.00041296918192730456
RMSE:  0.020321643189646466
****************************************************************************************************

In [ ]:
for symbol,model in company_model.items():
  latest_closing_price=company_data[symbol]['Close'].iloc[-1]
  latest_data=pd.DataFrame({'Close':[latest_closing_price]})
  predicted_price=model.predict(latest_data)
  print("Predicted price for",symbol,"next day:",predicted_price[0])

Predicted price for AAPL next day: 271.26478366899374
Predicted price for MSFT next day: 425.149641527916
Predicted price for GOOGL next day: 344.50626742984264
Predicted price for AMZN next day: 262.5593942424489
Predicted price for TSLA next day: 376.1160333198443
Predicted price for NVDA next day: 207.70145843210935
Predicted price for JPM next day: 307.80859776757495
Predicted price for GS next day: 926.081672545161
Predicted price for WMT next day: 129.94662679027397
Predicted price for KO next day: 76.6493149064522

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:839: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  array = numpy.asarray(array, order=order, dtype=dtype)